const mongoose = require("mongoose");

const auditSchema = new mongoose.Schema({
  tools: [
    {
      name: String,
      currentPlan: String,
      monthlyCost: Number,
      teamSize: Number,
      useCase: String,
      recommendedAlternative: String,
      alternativeCost: Number,
      monthlySavings: Number, // calculated: (current - alternative) * teamSize
      yearlySavings: Number, // monthlySavings * 12
    },
  ],
  totalMonthlySavings: Number,
  totalYearlySavings: Number,
  aiSummary: String, // Generated by API
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model("Audit", auditSchema);
